---
title: "Top 10 Artists by Total Streams"
execute: 
  echo: false
---

```{r}
#| message: false
library(tidyverse)
```

```{r}
#| message: false
x <- read_csv("Most Streamed Spotify Songs 2024.csv")
```

```{r}
#| message: false
# Calculate total streams by artist
artist_streams <- x %>%
  group_by(Artist) %>%
  summarise(TotalStreams = sum(`Spotify Streams`)) %>%
  arrange(desc(TotalStreams)) %>%
  head(10)

# Create the plot
plot <- ggplot(artist_streams, aes(x = reorder(Artist, TotalStreams), y = TotalStreams)) +
  geom_bar(stat = "identity", fill = "orange") +
  geom_text(aes(label = scales::comma(TotalStreams, accuracy = 1)), 
            hjust = 1.05, 
            color = "black",
            size = 4) +
  labs(
       x = "Artist",
       y = "Total Streams") +
  scale_y_continuous(labels = scales::comma) +
  coord_flip() +
  theme_minimal(base_size = 20) +
  theme(
    axis.title.x = element_text(margin = margin(t = 10), size = 14),
    axis.title.y = element_text(margin = margin(r = 10), size = 14),
    axis.text.y = element_text(face = "bold", size = 10),
    axis.text.x = element_text(angle = 0, hjust = 1, size = 10),
    panel.grid.major = element_line(color = "grey80"),
    panel.grid.minor = element_blank(),
    plot.margin = unit(c(1, 0.05, 1, 1), "cm") # Increase right margin significantly
  )

# Save the plot with a larger size
ggsave("Top10ArtistsByTotalStreams.png", plot = plot, width = 40, height = 10)

# Display the plot
print(plot)
```

